language: node_js
node_js:
  - 10
  - 12
  - '13'

before_install:
  - test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
  - if [ ! -d "$HOME/.pyenv" ]; then curl https://pyenv.run | bash; fi
  - export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
  - eval "$(pyenv init --path)"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 2.7.18 || true
  - pyenv global 2.7.18
  - python --version
install:
  - yarn 

script:
  - yarn lint
  - yarn test --retries 1

branches:
    only:
      - main

matrix:
    include:
      - node_js: 10
        env: TEST_SUITE=node-canvas
        addons:
            apt:
                packages:
                  - build-essential
                  - libcairo2-dev
                  - libpango1.0-dev
                  - libjpeg-dev
                  - libgif-dev
                  - librsvg2-dev
        script: "yarn add canvas && yarn test --retries 1"
      - node_js: stable
        env: TEST_SUITE=browser
        addons:
            chrome: stable
        script: "yarn test-browser"
