language: node_js
node_js:
  - 10
  - 12
  - '13'

before_install:
  - test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
  - sudo apt-get update
  - sudo apt-get remove -y python3 python3-pip
  - sudo apt-get install -y python2.7 python-pip
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
  - sudo update-alternatives --config python
  - python --version
install:
  - yarn 

script:
  - yarn lint
  - yarn test --retries 1

branches:
    only:
      - main

matrix:
    include:
      - node_js: 10
        env: TEST_SUITE=node-canvas
        addons:
            apt:
                packages:
                  - build-essential
                  - libcairo2-dev
                  - libpango1.0-dev
                  - libjpeg-dev
                  - libgif-dev
                  - librsvg2-dev
        script: "yarn add canvas && yarn test --retries 1"
      - node_js: stable
        env: TEST_SUITE=browser
        addons:
            chrome: stable
        script: "yarn test-browser"
